name: dig_proto
description: Protocol Buffer definitions for Dig Project
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  protobuf: ^6.0.0
  fixnum: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
